local INVENTORY_SIDE = "right"

local REDSTONE_OUTPUT_SIDE = "left"

local STOP_KEY = keys.q

return {INVENTORY_SIDE = INVENTORY_SIDE, REDSTONE_OUTPUT_SIDE = REDSTONE_OUTPUT_SIDE, STOP_KEY = STOP_KEY}